namespace ChaosCardGenerator;

/// <summary>
/// v111 official names, reviewed card by card. Chinese slashes mark deliberately chosen reusable
/// morphemes; English fields are explicit prefix / non-empty stem / suffix splits.
/// </summary>
internal static class ManualExternalNameParts
{
    internal static IEnumerable<NameParts> All() => Defect().Concat(Necrobinder()).Concat(Regent()).Concat(Colorless());

    private static IEnumerable<NameParts> Defect() => new[]
    {
        P("AdaptiveStrike", "适应/打击", "", "Adaptive", " Strike"),
        P("AllForOne", "万物/一心", "All for ", "One", ""),
        P("BallLightning", "球状/闪电", "Ball ", "Lightning", ""),
        P("Barrage", "弹幕/齐射", "", "Barr", "age"),
        P("BeamCell", "光束/射线", "Beam ", "Cell", ""),
        P("BiasedCognition", "偏差/认知", "Biased ", "Cognition", ""),
        P("BoostAway", "高速/脱离", "Boost ", "Away", ""),
        P("BootSequence", "启动/流程", "Boot ", "Sequence", ""),
        P("Buffer", "缓/冲", "", "Buff", "er"),
        P("BulkUp", "暴/涨", "Bulk ", "Up", ""),
        P("Capacitor", "扩/容", "", "Capacit", "or"),
        P("Chaos", "混/沌", "", "Chaos", ""),
        P("ChargeBattery", "充/电", "Charge ", "Battery", ""),
        P("Chill", "冰/寒", "", "Chill", ""),
        P("Claw", "爪/击", "", "Claw", ""),
        P("ColdSnap", "寒/流", "Cold ", "Snap", ""),
        P("Compact", "压/缩", "Com", "pact", ""),
        P("CompileDriver", "编译/冲击", "Compile ", "Driver", ""),
        P("ConsumingShadow", "吞噬/暗影", "Consuming ", "Shadow", ""),
        P("Coolant", "冷却/剂", "", "Cool", "ant"),
        P("Coolheaded", "冷静/头脑", "Cool", "head", "ed"),
        P("CreativeAi", "创造/性/AI", "Creative ", "AI", ""),
        P("Darkness", "漆/黑", "", "Dark", "ness"),
        P("DefendDefect", "防/御", "", "Defend", ""),
        P("Defragment", "碎片/整理", "De", "fragment", ""),
        P("DoubleEnergy", "双倍/能量", "Double ", "Energy", ""),
        P("Dualcast", "双重/释放", "Dual", "cast", ""),
        P("EchoForm", "回响/形态", "Echo ", "Form", ""),
        P("Feral", "野/性", "", "Fer", "al"),
        P("FightThrough", "强/撑", "Fight ", "Through", ""),
        P("FlakCannon", "散射/炮", "Flak ", "Cannon", ""),
        P("FocusedStrike", "集中/打击", "", "Focused", " Strike"),
        P("Ftl", "超越/光速", "", "FTL", ""),
        P("Fusion", "聚/变", "", "Fus", "ion"),
        P("GeneticAlgorithm", "遗传/算法", "Genetic ", "Algorithm", ""),
        P("Glacier", "冰/川", "", "Glaci", "er"),
        P("Glasswork", "玻璃/工艺", "Glass", "work", ""),
        P("GoForTheEyes", "眼部/攻击", "Go for the ", "Eyes", ""),
        P("GunkUp", "污秽/攻击", "Gunk ", "Up", ""),
        P("Hailstorm", "冰雹/风暴", "Hail", "storm", ""),
        P("HelixDrill", "螺旋/钻击", "Helix ", "Drill", ""),
        P("Hologram", "全息/影像", "Holo", "gram", ""),
        P("Hotfix", "热/修复", "Hot", "fix", ""),
        P("Hyperbeam", "超能/光束", "Hyper", "beam", ""),
        P("IceLance", "冰之/长枪", "Ice ", "Lance", ""),
        P("Iteration", "迭/代", "", "Iterat", "ion"),
        P("Leap", "飞/跃", "", "Leap", ""),
        P("LightningRod", "引雷/针", "Lightning ", "Rod", ""),
        P("Loop", "循/环", "", "Loop", ""),
        P("MachineLearning", "机器/学习", "Machine ", "Learning", ""),
        P("MeteorStrike", "陨石/打击", "", "Meteor", " Strike"),
        P("Modded", "模组/改造", "", "Mod", "ded"),
        P("MomentumStrike", "趁势/打击", "", "Momentum", " Strike"),
        P("MultiCast", "多重/释放", "Multi-", "Cast", ""),
        P("Null", "空/值", "", "Null", ""),
        P("Overclock", "超/频", "Over", "clock", ""),
        P("Quadcast", "四重/释放", "Quad", "cast", ""),
        P("Rainbow", "彩/虹", "", "Rain", "bow"),
        P("Reboot", "重/启", "Re", "boot", ""),
        P("Refract", "折/射", "Re", "fract", ""),
        P("RocketPunch", "火箭/飞拳", "Rocket ", "Punch", ""),
        P("Scavenge", "内存/清理", "", "Scaveng", "e"),
        P("Scrape", "刮/削", "", "Scrape", ""),
        P("ShadowShield", "暗影/之盾", "Shadow ", "Shield", ""),
        P("Shatter", "打/碎", "", "Shatt", "er"),
        P("SignalBoost", "信号/增强", "Signal ", "Boost", ""),
        P("Skim", "快速/检索", "", "Skim", ""),
        P("Smokestack", "烟/囱", "Smoke", "stack", ""),
        P("Spinner", "旋转/工艺", "", "Spinn", "er"),
        P("Storm", "雷/暴", "", "Storm", ""),
        P("StrikeDefect", "打击", "", "Defect", " Strike"),
        P("Subroutine", "子/程序", "Sub", "routine", ""),
        P("Sunder", "分/离", "", "Sunder", ""),
        P("Supercritical", "超临/界态", "Super", "critical", ""),
        P("SweepingBeam", "扫荡/射线", "Sweeping ", "Beam", ""),
        P("Synchronize", "同/步", "Syn", "chronize", ""),
        P("Synthesis", "人工/合成", "Syn", "thesis", ""),
        P("Tempest", "暴风/雨", "", "Tempest", ""),
        P("TeslaCoil", "特斯/拉/线圈", "Tesla ", "Coil", ""),
        P("Thunder", "雷/霆", "", "Thunder", ""),
        P("TrashToTreasure", "化废/为宝", "Trash to ", "Treasure", ""),
        P("Turbo", "内核/加速", "", "TURBO", ""),
        P("Uproar", "骚/动", "Up", "roar", ""),
        P("Voltaic", "电流/相生", "", "Volt", "aic"),
        P("WhiteNoise", "白/噪声", "White ", "Noise", ""),
        P("Zap", "电/击", "", "Zap", "")
    };

    private static IEnumerable<NameParts> Necrobinder() => new[]
    {
        P("Afterlife", "来/生", "After", "life", ""),
        P("BansheesCry", "女妖/之嚎", "Banshee's ", "Cry", ""),
        P("BlightStrike", "荒疫/打击", "", "Blight", " Strike"),
        P("Bodyguard", "护/卫", "Body", "guard", ""),
        P("BoneShards", "碎/骨", "Bone ", "Shards", ""),
        P("BorrowedTime", "预借/时间", "Borrowed ", "Time", ""),
        P("Bury", "埋/葬", "", "Bury", ""),
        P("Calcify", "钙/化", "", "Calc", "ify"),
        P("CallOfTheVoid", "虚空/之唤", "Call of the ", "Void", ""),
        P("CaptureSpirit", "捕捉/灵魂", "Capture ", "Spirit", ""),
        P("Cleanse", "洁/净", "", "Cleanse", ""),
        P("Countdown", "倒数/计时", "Count", "down", ""),
        P("DanseMacabre", "死亡/之舞", "Danse ", "Macabre", ""),
        P("DeathMarch", "死亡/行军", "Death ", "March", ""),
        P("Deathbringer", "死亡/使者", "Death", "bring", "er"),
        P("DeathsDoor", "死亡/之门", "Death's ", "Door", ""),
        P("Debilitate", "摧/残", "De", "bilit", "ate"),
        P("DefendNecrobinder", "防/御", "", "Defend", ""),
        P("Defile", "玷/污", "De", "file", ""),
        P("Defy", "违/逆", "De", "fy", ""),
        P("Delay", "拖/延", "De", "lay", ""),
        P("Demesne", "领/域", "", "Demesne", ""),
        P("DevourLife", "吞噬/生命", "Devour ", "Life", ""),
        P("Dirge", "挽/歌", "", "Dirge", ""),
        P("DrainPower", "能量/汲取", "Drain ", "Power", ""),
        P("Dredge", "清/淤", "", "Dredge", ""),
        P("Eidolon", "幻/景", "", "Eidol", "on"),
        P("EndOfDays", "末日/降临", "End of ", "Days", ""),
        P("EnfeeblingTouch", "弱化/之触", "Enfeebling ", "Touch", ""),
        P("Eradicate", "根/除", "E", "radic", "ate"),
        P("Fear", "恐/惧", "", "Fear", ""),
        P("Fetch", "取/回", "", "Fetch", ""),
        P("Flatten", "重/压", "", "Flatt", "en"),
        P("ForbiddenGrimoire", "禁忌/魔典", "Forbidden ", "Grimoire", ""),
        P("Friendship", "友/谊", "Friend", "ship", ""),
        P("GraveWarden", "守墓/人", "Grave ", "Warden", ""),
        P("Graveblast", "坟冢/爆射", "Grave", "blast", ""),
        // The Chinese title for Hang must remain one indivisible chunk; English keeps its reviewed morphology.
        P("Hang", "吊杀", "", "Hang", ""),
        P("Haunt", "纠/缠", "", "Haunt", ""),
        P("HighFive", "击/掌", "High ", "Five", ""),
        P("Invoke", "唤/起", "In", "voke", ""),
        P("Lethality", "致死/性", "Lethal", "ity", ""),
        P("Melancholy", "忧/郁", "", "Melanchol", "y"),
        P("Misery", "苦/难", "", "Miser", "y"),
        P("NecroMastery", "亡灵/精通", "Necro ", "Mastery", ""),
        P("NegativePulse", "负/能量/脉冲", "Negative ", "Pulse", ""),
        P("Neurosurge", "精神/过载", "Neuro", "surge", ""),
        P("NoEscape", "无处/可逃", "No ", "Escape", ""),
        P("Oblivion", "湮/灭", "", "Obliv", "ion"),
        P("Pagestorm", "书页/风暴", "Page", "storm", ""),
        P("Parse", "领/会", "", "Parse", ""),
        P("Poke", "戳/击", "", "Poke", ""),
        P("Protector", "守护/者", "Protect", "or", ""),
        P("PullAggro", "吸引/仇恨", "Pull ", "Aggro", ""),
        P("PullFromBelow", "亡魂/牵引", "Pull from ", "Below", ""),
        P("Putrefy", "腐/败", "", "Putre", "fy"),
        P("Rattle", "猛/晃", "", "Rattle", ""),
        P("Reanimate", "死者/苏生", "Re", "anim", "ate"),
        P("Reap", "收/割", "", "Reap", ""),
        P("ReaperForm", "死神/形态", "Reaper ", "Form", ""),
        P("Reave", "剥/夺", "", "Reave", ""),
        P("RightHandHand", "得力/助手", "Right Hand ", "Hand", ""),
        P("Sacrifice", "牺/牲", "", "Sacrif", "ice"),
        P("Scourge", "鞭/打", "", "Scourge", ""),
        P("SculptingStrike", "雕琢/打击", "", "Sculpting", " Strike"),
        P("Seance", "降/灵", "", "Seance", ""),
        P("SentryMode", "哨卫/模式", "Sentry ", "Mode", ""),
        P("Severance", "切/断", "", "Sever", "ance"),
        P("SharedFate", "命运/同担", "Shared ", "Fate", ""),
        P("Shroud", "厄运/之衣", "", "Shroud", ""),
        P("SicEm", "紧追/不放", "Sic ", "'Em", ""),
        P("SleightOfFlesh", "血肉/戏法", "Sleight of ", "Flesh", ""),
        P("Snap", "响/指", "", "Snap", ""),
        P("SoulStorm", "灵魂/风暴", "Soul ", "Storm", ""),
        P("Sow", "播/种", "", "Sow", ""),
        P("SpiritOfAsh", "灰烬/之灵", "Spirit of ", "Ash", ""),
        P("Spur", "增/生", "", "Spur", ""),
        P("Squeeze", "榨/取", "", "Squeeze", ""),
        P("StrikeNecrobinder", "打击", "", "Necrobinder", " Strike"),
        P("TheScythe", "巨/镰", "The ", "Scythe", ""),
        P("TimesUp", "大限/已至", "Time's ", "Up", ""),
        P("Transfigure", "重/构", "Trans", "figure", ""),
        P("Undeath", "不/死", "Un", "death", ""),
        P("Unleash", "出/击", "Un", "leash", ""),
        P("Veilpiercer", "刺破/帷幕", "Veil", "pierc", "er"),
        P("Wisp", "鬼/火", "", "Wisp", "")
    };

    private static IEnumerable<NameParts> Regent() => new[]
    {
        P("Alignment", "星位/序列", "", "Align", "ment"),
        P("Arsenal", "武器/库", "", "Arsen", "al"),
        P("AstralPulse", "星界/脉冲", "Astral ", "Pulse", ""),
        P("BeatIntoShape", "锻打/成型", "Beat into ", "Shape", ""),
        P("Begone", "下/去！", "", "BEGONE", "!"),
        P("BigBang", "大/爆炸", "Big ", "Bang", ""),
        P("BlackHole", "黑/洞", "Black ", "Hole", ""),
        P("Bombardment", "轰/击", "", "Bombard", "ment"),
        P("Bulwark", "铸/墙", "", "Bulwark", ""),
        P("BundleOfJoy", "新生/之喜", "Bundle of ", "Joy", ""),
        P("CelestialMight", "天穹/之力", "Celestial ", "Might", ""),
        P("Charge", "冲锋/！！", "", "CHARGE", "!!"),
        P("ChildOfTheStars", "群星/之子", "Child of the ", "Stars", ""),
        P("CloakOfStars", "群星/斗篷", "Cloak of ", "Stars", ""),
        P("CollisionCourse", "碰撞/轨迹", "Collision ", "Course", ""),
        P("Comet", "彗/星", "", "Comet", ""),
        P("Conqueror", "征服/者", "", "Conquer", "or"),
        P("Convergence", "汇/流", "Con", "verg", "ence"),
        P("CosmicIndifference", "宇宙/冷漠", "Cosmic ", "Indifference", ""),
        P("CrashLanding", "迫/降", "Crash ", "Landing", ""),
        P("CrescentSpear", "新月/长矛", "Crescent ", "Spear", ""),
        P("CrushUnder", "下/砸", "Crush ", "Under", ""),
        P("DecisionsDecisions", "抉择/，/抉择", "Decisions, ", "Decisions", ""),
        P("DefendRegent", "防/御", "", "Defend", ""),
        P("Devastate", "葬/送", "", "Devast", "ate"),
        P("DyingStar", "星/灭", "Dying ", "Star", ""),
        P("FallingStar", "陨/星", "Falling ", "Star", ""),
        P("ForegoneConclusion", "既定/事项", "Foregone ", "Conclusion", ""),
        P("Furnace", "熔/炉", "", "Furnace", ""),
        P("GammaBlast", "伽马/爆破", "Gamma ", "Blast", ""),
        P("GatherLight", "收集/光辉", "Gather ", "Light", ""),
        P("Genesis", "创世/纪", "", "Genes", "is"),
        P("Glimmer", "微/光", "", "Glimm", "er"),
        P("Glitterstream", "流光/溢彩", "Glitter", "stream", ""),
        P("Glow", "辉/光", "", "Glow", ""),
        P("Guards", "护驾/！！/！", "", "GUARDS", "!!!"),
        P("GuidingStar", "引导/之星", "Guiding ", "Star", ""),
        P("HeavenlyDrill", "天际/钻头", "Heavenly ", "Drill", ""),
        P("Hegemony", "霸/权", "", "Hegemon", "y"),
        P("HeirloomHammer", "传承/之锤", "Heirloom ", "Hammer", ""),
        P("HiddenCache", "隐秘/藏品", "Hidden ", "Cache", ""),
        P("IAmInvincible", "所向/无敌", "I Am ", "Invincible", ""),
        P("KinglyKick", "王者/之踢", "Kingly ", "Kick", ""),
        P("KinglyPunch", "王者/之拳", "Kingly ", "Punch", ""),
        P("KnockoutBlow", "决胜/一击", "Knockout ", "Blow", ""),
        P("KnowThyPlace", "何人/僭越", "Know Thy ", "Place", ""),
        P("LunarBlast", "月面/射击", "Lunar ", "Blast", ""),
        P("MakeItSo", "如此/甚好", "Make It ", "So", ""),
        P("ManifestAuthority", "君权/自授", "Manifest ", "Authority", ""),
        P("MeteorShower", "流星/雨", "Meteor ", "Shower", ""),
        P("MonarchsGaze", "王之/凝视", "Monarch's ", "Gaze", ""),
        P("Monologue", "独/白", "Mono", "logue", ""),
        P("NeutronAegis", "中子/护盾", "Neutron ", "Aegis", ""),
        P("Orbit", "环绕/轨道", "", "Orbit", ""),
        P("PaleBlueDot", "暗淡/蓝点", "Pale Blue ", "Dot", ""),
        P("Parry", "招/架", "", "Parry", ""),
        P("ParticleWall", "粒子/墙", "Particle ", "Wall", ""),
        P("Patter", "星星/点点", "", "Patter", ""),
        P("PhotonCut", "光子/切割", "Photon ", "Cut", ""),
        P("PillarOfCreation", "创世/之柱", "Pillar of ", "Creation", ""),
        P("Prophesize", "预/言", "", "Prophes", "ize"),
        P("Quasar", "类星/体", "", "Quasar", ""),
        P("Radiate", "辐/射", "", "Radi", "ate"),
        P("RefineBlade", "淬炼/刀刃", "Refine ", "Blade", ""),
        P("Reflect", "倒/映", "Re", "flect", ""),
        P("Resonance", "共/鸣", "", "Reson", "ance"),
        P("RoyalGamble", "胜券/在王", "Royal ", "Gamble", ""),
        P("Royalties", "王国/资产", "", "Royal", "ties"),
        P("SeekingEdge", "追踪/之刃", "Seeking ", "Edge", ""),
        P("SevenStars", "七/星", "Seven ", "Stars", ""),
        P("ShiningStrike", "明耀/打击", "", "Shining", " Strike"),
        P("SolarStrike", "太阳/打击", "", "Solar", " Strike"),
        P("SpectrumShift", "光谱/偏移", "Spectrum ", "Shift", ""),
        P("SpoilsOfBattle", "战利/品", "Spoils of ", "Battle", ""),
        P("Stardust", "星/尘", "Star", "dust", ""),
        P("StrikeRegent", "打击", "", "Regent", " Strike"),
        P("SummonForth", "征召/上前", "Summon ", "Forth", ""),
        P("Supermassive", "超质/量体", "Super", "massive", ""),
        P("SwordSage", "剑/圣", "Sword ", "Sage", ""),
        P("Terraforming", "地形/改造", "Terra", "form", "ing"),
        P("TheSealedThrone", "封印/王座", "The Sealed ", "Throne", ""),
        P("TheSmith", "铸剑/者", "The ", "Smith", ""),
        P("Tyranny", "暴/政", "", "Tyrann", "y"),
        P("Venerate", "崇/拜", "", "Vener", "ate"),
        P("VoidForm", "虚空/形态", "Void ", "Form", ""),
        P("WroughtInWar", "战火/铸就", "Wrought in ", "War", "")
    };

    private static IEnumerable<NameParts> Colorless() => new[]
    {
        P("Alchemize", "炼制/药水", "Al", "chem", "ize"),
        P("Anointed", "天/选", "An", "oint", "ed"),
        P("Automation", "自动/化", "Auto", "mat", "ion"),
        P("BeatDown", "狠/揍", "Beat ", "Down", ""),
        P("Bolas", "流星/锤", "", "Bolas", ""),
        P("Calamity", "劫/难", "", "Calam", "ity"),
        P("Catastrophe", "横/祸", "Cata", "stroph", "e"),
        P("DarkShackles", "黑暗/镣铐", "Dark ", "Shackles", ""),
        P("Discovery", "发/现", "Dis", "cover", "y"),
        P("DramaticEntrance", "闪亮/登场", "Dramatic ", "Entrance", ""),
        P("Entropy", "熵", "", "Entropy", ""),
        P("Equilibrium", "均/衡", "Equi", "libr", "ium"),
        P("EternalArmor", "永恒/铠甲", "Eternal ", "Armor", ""),
        P("Finesse", "妙/计", "", "Finesse", ""),
        P("Fisticuffs", "拳/斗", "Fisti", "cuff", "s"),
        P("FlashOfSteel", "亮/剑", "Flash of ", "Steel", ""),
        P("GoldAxe", "金/斧", "Gold ", "Axe", ""),
        P("HandOfGreed", "贪婪/之手", "Hand of ", "Greed", ""),
        P("HiddenGem", "未掘/宝石", "Hidden ", "Gem", ""),
        P("Impatience", "急/躁", "Im", "patience", ""),
        P("JackOfAllTrades", "花样/百出", "Jack of All ", "Trades", ""),
        P("Jackpot", "大/奖", "Jack", "pot", ""),
        P("MasterOfStrategy", "战略/大师", "Master of ", "Strategy", ""),
        P("Mayhem", "乱/战", "", "Mayhem", ""),
        P("MindBlast", "心灵/震慑", "Mind ", "Blast", ""),
        P("Nostalgia", "怀/旧", "", "Nostalgi", "a"),
        P("Omnislice", "万向/斩", "Omni", "slice", ""),
        P("Panache", "神气/制胜", "", "Panache", ""),
        P("PanicButton", "应急/按钮", "Panic ", "Button", ""),
        P("PrepTime", "准备/时间", "Prep ", "Time", ""),
        P("Production", "生产/制造", "Pro", "duct", "ion"),
        P("Prolong", "延/伸", "Pro", "long", ""),
        P("Prowess", "非凡/技艺", "", "Prowess", ""),
        P("Purity", "净/化", "", "Pur", "ity"),
        P("Rend", "撕/碎", "", "Rend", ""),
        P("Restlessness", "心神/不宁", "Rest", "less", "ness"),
        P("RollingBoulder", "滚/石", "Rolling ", "Boulder", ""),
        P("Salvo", "箭/雨", "", "Salvo", ""),
        P("Scrawl", "潦草/急就", "", "Scrawl", ""),
        P("SecretTechnique", "秘密/技法", "Secret ", "Technique", ""),
        P("SecretWeapon", "秘密/武器", "Secret ", "Weapon", ""),
        P("SeekerStrike", "探寻/打击", "", "Seeker", " Strike"),
        P("Shockwave", "震荡/波", "Shock", "wave", ""),
        P("Splash", "飞/溅", "", "Splash", ""),
        P("Stratagem", "计/策", "", "Stratagem", ""),
        P("TheBomb", "炸/弹", "The ", "Bomb", ""),
        P("TheGambit", "孤注/一掷", "The ", "Gambit", ""),
        P("ThinkingAhead", "深谋/远虑", "Thinking ", "Ahead", ""),
        P("ThrummingHatchet", "无休/手斧", "Thrumming ", "Hatchet", ""),
        P("UltimateDefend", "究极/防御", "Ultimate ", "Defend", ""),
        P("UltimateStrike", "究极/打击", "", "Ultimate", " Strike"),
        P("Volley", "连/射", "", "Volley", "")
    };

    private static NameParts P(string id, string chinese, string prefix, string middle, string suffix) =>
        new(id, chinese.Split('/', StringSplitOptions.RemoveEmptyEntries), prefix, middle, suffix);
}
